CREATE DATABASE FUEL_DB;
USE FUEL_DB;

DROP TABLE IF EXISTS GAS_STATION;

CREATE TABLE GAS_STATION (

	ID INT NOT NULL AUTO_INCREMENT,
	CALLE VARCHAR(100),
	RFC VARCHAR(100),
	DATE_INSERTED VARCHAR(100),
	REGULAR VARCHAR(100),
	COLONIA VARCHAR(100),
	NUMERO_PERMISO VARCHAR(100),
	FECHA_APLICACION VARCHAR(100),
	PERMISO_ID VARCHAR(100),
	LONGITUDE VARCHAR(100),
	LATITUDE VARCHAR (100),
	PREMIUM VARCHAR (100),
	RAZON_SOCIAL VARCHAR (100),
	CODIGO_POSTAL VARCHAR (100),
	DIESEL VARCHAR (100),
	PRIMARY KEY ( ID )
);
